spring:
  profiles:
    active: ${PROFILE}
    include: database, jasypt
  application:
    name: diary
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
#  config: classpath:logs/logback-local.xml
  level:
    sql: debug
server:
  port: ${SERVER_PORT}
management:
  server:
    port: ${SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true